# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
<<<<<<< HEAD
title: HyG
brief-intro: Front-end Dev Engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gaohaoyang.github.io" # the base hostname & protocol for your site
=======
title: XG
brief-intro: Openstack Cloud Dev Engineer
baseurl: "/xugangit" # the subpath of your site, e.g. /blog
url: "http://xugangit.github.io" # the base hostname & protocol for your site
>>>>>>> 9e85fd53969e5e10d1634eb89f6f7233a66415d5

permalink: /:year/:month/:day/:title/

# other links
<<<<<<< HEAD
twitter_username: gaohaoyang126
facebook_username: gaohaoyang.water
github_username:  Gaohaoyang
email: gaohaoyang126@126.com
weibo_username: 3115521wh
zhihu_username: gaohaoyang
linkedIn_username: gaohaoyang
dribbble_username: 

description_footer: 本站记录我前端之旅的沿途风景！
=======
twitter_username: xugangit@126.com
facebook_username: xugangit@126.com
github_username:  xugangit@126.com
email: xugangit@126.com
weibo_username: xugangit@126.com
zhihu_username: xugangit@126.com
linkedIn_username: xugangit@126.com
dribbble_username: 

description_footer: 在IT领域，不断的摸爬滚打
>>>>>>> 9e85fd53969e5e10d1634eb89f6f7233a66415d5

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
duoshuo_shortname: #hygblog
<<<<<<< HEAD
disqus_shortname: gaohaoyang
=======
disqus_shortname: xugangit
>>>>>>> 9e85fd53969e5e10d1634eb89f6f7233a66415d5

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
<<<<<<< HEAD
baidu_tongji_id: cf8506e0ef223e57ff6239944e5d46a4
google_analytics_id: UA-72449510-4 # google 分析追踪id
=======
baidu_tongji_id: 1e58fc95f8da5b43df1dfe78559a61be
google_analytics_id: UA-80999573-1 # google 分析追踪id
>>>>>>> 9e85fd53969e5e10d1634eb89f6f7233a66415d5

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 5
